# Site settings
title: Mind2you | minder
email: mind2you@aliyun.com
description: > # this means to ignore newlines until "baseurl:"
  minder
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mind2you.github.io" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag'
tags: [About, Document]


# Social account
# twitter:  username
# weibo:    ID
github:   mind2you
# codepen:  username
# dribbble: username


# Comment
# disqus_shortname: discussion_shortname


# Google Analytics
# google_analytics: tracking_ID


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
